$(function(){
    setTimeout(function(){
        $('.left').animate({'left':'15%'},1000);
        $('.right').animate({'right':'15%'},1000);
    },1000);
    setTimeout(function(){
        $('.a1').show().animate({
            'left':"10%",
            'top':'70%',
            'margin':'0',
            'width':'10%',
            'height':'20%'
        },500,function(){
            $('.a2').show().animate({
                'left':"24%",
                'top':'70%',
                'margin':'0',
                'width':'10%',
                'height':'20%'
            },500,function(){
                $('.a3').show().animate({
                    'left':"38%",
                    'top':'70%',
                    'margin':'0',
                    'width':'10%',
                    'height':'20%'
                },500,function(){
                    $('.a4').show().animate({
                        'left':"52%",
                        'top':'70%',
                        'margin':'0',
                        'width':'10%',
                        'height':'20%'
                    },500,function(){
                        $('.a5').show().animate({
                            'left':"66%",
                            'top':'70%',
                            'margin':'0',
                            'width':'10%',
                            'height':'20%'
                        },500,function(){
                            $('.a6').show().animate({
                                'left':"80%",
                                'top':'70%',
                                'margin':'0',
                                'width':'10%',
                                'height':'20%'
                            },500)
                        })
                    })
                })
            })
        })
    },2000);
    $('.Ta').click(function(){
        window.location.href = '../html/page1.html'
    })
})